set -g default-terminal "tmux-256color"
set -as terminal-features ",tmux-256color:RGB"
set -ag terminal-overrides ",xterm-256color:RGB"
set -s escape-time 0

# unbind stupid thing
unbind-key C-\\
unbind -n C-\\

# change prefix
unbind C-b
set -g prefix C-Space
bind-key C-Space send-prefix

# start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1

# reload
unbind r
bind r source-file ~/.tmux.conf

# creating panes
unbind %
bind \\ split-window -h

unbind '"'
bind - split-window -v

# vim-like pane switching
bind -r ^ last-window
bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r h resize-pane -L 5

bind m resize-pane -Z

# session picker
bind-key -r f run-shell 'sesh connect "$(sesh list --icons | fzf-tmux -p 80%,70% \
  --no-sort --ansi --border-label " sesh " --prompt "⚡  " \
  --header "  ^a all ^t tmux ^g configs ^x zoxide ^d tmux kill ^f find" \
  --bind "tab:down,btab:up" \
  --bind "ctrl-a:change-prompt(⚡  )+reload(sesh list --icons)" \
  --bind "ctrl-t:change-prompt(🪟  )+reload(sesh list -t --icons)" \
  --bind "ctrl-g:change-prompt(⚙️  )+reload(sesh list -c --icons)" \
  --bind "ctrl-x:change-prompt(📁  )+reload(sesh list -z --icons)" \
  --bind "ctrl-d:execute(tmux kill-session -t {2..})+change-prompt(⚡  )+reload(sesh list --icons)" \
  --bind "ctrl-f:change-prompt(🔎  )+reload(fd -H -d 4 -t d -E .Trash -E Library -E .git -E node_modules -E .cache ~)" \
  --preview-window "right:55%" \
  --preview "sesh preview {}")"'

# window picker
bind-key "W" run-shell "sesh window \"$(sesh window | fzf-tmux -p 60%,50% --prompt '🪟  ')\""

# sesh recommendations
bind-key x kill-pane # skip "kill-pane 1? (y/n)" prompt
set -g detach-on-destroy off  # don't exit from tmux when closing a session
bind -N "last-session (via sesh) " L run-shell "sesh last" # always find last session
set-hook -g session-created 'run-shell -b "sesh rename --enrich"' # add issue name (shouldn't hurt)
# git worktrees i think?
bind -N "switch to root session (via sesh) " 9 run-shell "sesh connect --root $(pwd)" # connect to root
bind-key "R" display-popup -E -w 40% "sesh connect \"$(
  sesh list -i -H | gum filter --value \"$(sesh root)\" --limit 1 --fuzzy --no-sort --placeholder 'Pick a sesh' --prompt='⚡'readme
)\""

# scripts
# bind-key -r f run-shell "tmux neww ~/.local/bin/tmux-sessionizer.sh"
bind-key -r X run-shell "~/.local/bin/tmux-clear-sessions.sh"

# clear
# Use prefix C-l to clear the visible scrollback lines
bind C-l send-keys 'C-l'

# Use prefix C-k to clear the scrolled off (hidden) buffer lines
bind C-k clear-history

set -g mouse on

set-window-option -g mode-keys vi

bind-key -T copy-mode-vi 'v' send -X begin-selection # start selecting text with "v"
bind-key -T copy-mode-vi 'C-v' send -X rectangle-toggle # Begin selection in copy mode.
bind-key -T copy-mode-vi 'y' send -X copy-selection # copy text with "y"

unbind -T copy-mode-vi MouseDragEnd1Pane # don't exit copy mode when dragging with mouse

# remove delay for exiting insert mode with ESC in Neovim
set -sg escape-time 10

# tpm plugin
set -g @plugin 'tmux-plugins/tpm'

# list of tmux plugins
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-resurrect' # persist tmux sessions after computer restart
set -g @plugin 'tmux-plugins/tmux-continuum' # automatically saves sessions for you every 15 minutes
set -g @plugin 'dracula/tmux'
set -g @dracula-plugins "cpu-usage ram-usage"
set -g @dracula-show-left-icon "#h | #S"
set -g @resurrect-capture-pane-contents 'on'
# set -g @continuum-restore 'on'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
