local ls = require("luasnip")
local s = ls.snippet
local t = ls.text_node
local i = ls.insert_node

ls.add_snippets("typst", {
  s("hw", {
    t({
      "#let conf(",
      "  class,",
      "  due,",
      "  title,",
      "  doc,",
      ") = {",
      "  set page(",
      "    header: {",
      "      grid(",
      "        columns: (1fr, auto, 1fr),",
      "        rows: (auto, auto),",
      "        align: (left, center, right),",
      "        inset: 4pt,",
      "        grid.cell(",
      "          rowspan: 2,",
      "          [#class \\ Due #due],",
      "        ),",
      "        [],",
      "        [],",
      "        text(size: 1.4em)[*#title*],",
      "        context { [#counter(page).display(\"1\")] },",
      "        grid.hline(stroke: 0.5pt),",
      "      )",
      "    },",
      "  )",
      "",
      "  doc",
      "}",
      "",
      "#let prob(number) = {",
      "  [#heading[Problem #number.]]",
      "}",
      "",
      "#let part(number) = {",
      "  [#heading(level: 2)[Part (#number)]]",
      "}",
      "",
      "#let sol = rect.with(stroke: black, inset: 1em)",
      "",
      "#show: doc => conf(",
      "  [",
    }),
    i(1, "CLASS"),
    t({ "],", "  [" }),
    i(2, "DUE DATE"),
    t({ "],", "  [" }),
    i(3, "TITLE"),
    t({
      "],",
      "  doc,",
      ")",
      "",
    }),
    i(0),
  }),
})
